// <auto-generated />
using System;
using DarkKitchen.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DarkKitchen.Infrastructure.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20260610114949_ExtendSeedPromotionDates")]
    partial class ExtendSeedPromotionDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DarkKitchen.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            ClientId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            CreatedAt = new DateTime(2026, 4, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryType = "Express",
                            Status = "Pending",
                            StatusChangedAt = new DateTime(2026, 4, 25, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            ClientId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            CreatedAt = new DateTime(2026, 4, 26, 11, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryType = "Express",
                            Status = "Ready",
                            StatusChangedAt = new DateTime(2026, 4, 26, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            ClientId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            CreatedAt = new DateTime(2026, 4, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryType = "TwentyFourHours",
                            Status = "Cancelled",
                            StatusChangedAt = new DateTime(2026, 4, 26, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            ClientId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            CreatedAt = new DateTime(2026, 4, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryType = "Express",
                            Status = "OnTheWay",
                            StatusChangedAt = new DateTime(2026, 4, 27, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            ClientId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            CreatedAt = new DateTime(2026, 4, 27, 16, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryType = "TwentyFourHours",
                            Status = "Delivered",
                            StatusChangedAt = new DateTime(2026, 4, 27, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            ClientId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            CreatedAt = new DateTime(2026, 4, 28, 8, 0, 0, 0, DateTimeKind.Utc),
                            DeliveryType = "Express",
                            Status = "NotDelivered",
                            StatusChangedAt = new DateTime(2026, 4, 28, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000004"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000005"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000013"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            OrderId = new Guid("30000000-0000-0000-0000-000000000006"),
                            ProductId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            PermissionName = "CanGetProduct"
                        },
                        new
                        {
                            PermissionId = 2,
                            PermissionName = "CanCreateProduct"
                        },
                        new
                        {
                            PermissionId = 3,
                            PermissionName = "CanUpdateProduct"
                        },
                        new
                        {
                            PermissionId = 4,
                            PermissionName = "CanDeleteProduct"
                        },
                        new
                        {
                            PermissionId = 5,
                            PermissionName = "CanGetCategory"
                        },
                        new
                        {
                            PermissionId = 6,
                            PermissionName = "CanCreateCategory"
                        },
                        new
                        {
                            PermissionId = 7,
                            PermissionName = "CanUpdateCategory"
                        },
                        new
                        {
                            PermissionId = 8,
                            PermissionName = "CanDeleteCategory"
                        },
                        new
                        {
                            PermissionId = 9,
                            PermissionName = "CanCreateOrder"
                        },
                        new
                        {
                            PermissionId = 10,
                            PermissionName = "CanGetClientOrders"
                        },
                        new
                        {
                            PermissionId = 11,
                            PermissionName = "CanGetOrders"
                        },
                        new
                        {
                            PermissionId = 12,
                            PermissionName = "CanGetOrderDetail"
                        },
                        new
                        {
                            PermissionId = 13,
                            PermissionName = "CanGetPromotion"
                        },
                        new
                        {
                            PermissionId = 14,
                            PermissionName = "CanCreatePromotion"
                        },
                        new
                        {
                            PermissionId = 15,
                            PermissionName = "CanUpdatePromotion"
                        },
                        new
                        {
                            PermissionId = 16,
                            PermissionName = "CanDeletePromotion"
                        },
                        new
                        {
                            PermissionId = 17,
                            PermissionName = "CanGetUsers"
                        },
                        new
                        {
                            PermissionId = 18,
                            PermissionName = "CanCreateUser"
                        },
                        new
                        {
                            PermissionId = 19,
                            PermissionName = "CanUpdateUser"
                        },
                        new
                        {
                            PermissionId = 20,
                            PermissionName = "CanDeleteUser"
                        },
                        new
                        {
                            PermissionId = 21,
                            PermissionName = "CanMarkOrderReady"
                        },
                        new
                        {
                            PermissionId = 22,
                            PermissionName = "CanCancelOrder"
                        },
                        new
                        {
                            PermissionId = 23,
                            PermissionName = "CanMarkOrderOnTheWay"
                        },
                        new
                        {
                            PermissionId = 24,
                            PermissionName = "CanDeliverOrder"
                        },
                        new
                        {
                            PermissionId = 25,
                            PermissionName = "CanMarkOrderNotDelivered"
                        },
                        new
                        {
                            PermissionId = 26,
                            PermissionName = "CanMarkOrderDelayed"
                        },
                        new
                        {
                            PermissionId = 27,
                            PermissionName = "CanGetTopProducts"
                        },
                        new
                        {
                            PermissionId = 28,
                            PermissionName = "CanGetSalesReport"
                        });
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Juicy beef patty with lettuce tomato and cheese",
                            Name = "Classic Burger",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Plant based patty with fresh vegetables and avocado",
                            Name = "Veggie Burger",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Crispy bacon with beef patty and cheddar",
                            Name = "Bacon Burger",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Classic tomato sauce with fresh mozzarella and basil",
                            Name = "Margherita",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Spicy pepperoni with tomato sauce and mozzarella",
                            Name = "Pepperoni",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Blend of mozzarella cheddar parmesan and gorgonzola",
                            Name = "Four Cheese",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Fresh salmon with rice and seaweed",
                            Name = "Salmon Roll",
                            Price = 11.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Sliced fresh tuna over seasoned rice",
                            Name = "Tuna Nigiri",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Crab avocado and cucumber wrapped in rice",
                            Name = "California Roll",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Romaine lettuce with parmesan and caesar dressing",
                            Name = "Caesar Salad",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Tomatoes cucumbers olives feta cheese and oregano",
                            Name = "Greek Salad",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Mixed greens with tomatoes carrots and vinaigrette",
                            Name = "Garden Salad",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Freshly squeezed lemon juice with sparkling water",
                            Name = "Lemonade",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Cold brew coffee with milk and ice",
                            Name = "Iced Coffee",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Freshly squeezed natural orange juice",
                            Name = "Orange Juice",
                            Price = 3.99m
                        });
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Fresh handcrafted burgers",
                            Name = "Burgers"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Stone oven baked pizzas",
                            Name = "Pizzas"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Fresh Japanese rolls and nigiri",
                            Name = "Sushi"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Light and fresh salads",
                            Name = "Salads"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Cold and hot drinks",
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            DiscountPercentage = 0.20m,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Summer Burger Deal",
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            DiscountPercentage = 0.15m,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pizza Fiesta",
                            StartDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            DiscountPercentage = 0.25m,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sushi Special",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Customer"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Dispatcher"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Administrator"
                        });
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Token");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            Email = "agustin.robaina@darkkitchen.com",
                            FirstName = "Agustin",
                            LastName = "Robaina",
                            Password = "D@rkK!tchen#2026",
                            Phone = "099000001",
                            RoleId = 3
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            Email = "francisco.topolansky@darkkitchen.com",
                            FirstName = "Francisco",
                            LastName = "Topolansky",
                            Password = "D@rkK!tchen#2026",
                            Phone = "099000002",
                            RoleId = 3
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3"),
                            Email = "manuel.font@darkkitchen.com",
                            FirstName = "Manuel",
                            LastName = "Font",
                            Password = "D@rkK!tchen#2026",
                            Phone = "099000003",
                            RoleId = 3
                        },
                        new
                        {
                            Id = new Guid("d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4"),
                            Email = "admin@darkkitchen.com",
                            FirstName = "Admin",
                            LastName = "User",
                            Password = "D@rkK!tchen#2026",
                            Phone = "099000004",
                            RoleId = 3
                        },
                        new
                        {
                            Id = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            Email = "customer@darkkitchen.com",
                            FirstName = "Customer",
                            LastName = "User",
                            Password = "D@rkK!tchen#2026",
                            Phone = "099000005",
                            RoleId = 1
                        },
                        new
                        {
                            Id = new Guid("f6f6f6f6-f6f6-f6f6-f6f6-f6f6f6f6f6f6"),
                            Email = "dispatcher@darkkitchen.com",
                            FirstName = "Dispatcher",
                            LastName = "User",
                            Password = "D@rkK!tchen#2026",
                            Phone = "099000006",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("ProductPromotions", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "PromotionId");

                    b.HasIndex("PromotionId");

                    b.ToTable("ProductPromotions");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("20000000-0000-0000-0000-000000000001"),
                            PromotionId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ProductId = new Guid("20000000-0000-0000-0000-000000000004"),
                            PromotionId = new Guid("50000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            ProductId = new Guid("20000000-0000-0000-0000-000000000007"),
                            PromotionId = new Guid("50000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 8,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 10,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 13,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 14,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 15,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 16,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 17,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 18,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 19,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 20,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 21,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 21,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 22,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 23,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 24,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 25,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 26,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 27,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 28,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.Order", b =>
                {
                    b.HasOne("DarkKitchen.Domain.Entities.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DarkKitchen.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Apartment")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Apartment");

                            b1.Property<int>("DoorNumber")
                                .HasColumnType("int")
                                .HasColumnName("DoorNumber");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Street");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.HasData(
                                new
                                {
                                    OrderId = new Guid("30000000-0000-0000-0000-000000000001"),
                                    DoorNumber = 100,
                                    Street = "Av Libertad"
                                },
                                new
                                {
                                    OrderId = new Guid("30000000-0000-0000-0000-000000000002"),
                                    Apartment = "A",
                                    DoorNumber = 220,
                                    Street = "Calle Rivera"
                                },
                                new
                                {
                                    OrderId = new Guid("30000000-0000-0000-0000-000000000003"),
                                    DoorNumber = 345,
                                    Street = "Rambla Sur"
                                },
                                new
                                {
                                    OrderId = new Guid("30000000-0000-0000-0000-000000000004"),
                                    Apartment = "B",
                                    DoorNumber = 450,
                                    Street = "Av Italia"
                                },
                                new
                                {
                                    OrderId = new Guid("30000000-0000-0000-0000-000000000005"),
                                    DoorNumber = 560,
                                    Street = "Bulevar Artigas"
                                },
                                new
                                {
                                    OrderId = new Guid("30000000-0000-0000-0000-000000000006"),
                                    DoorNumber = 672,
                                    Street = "Calle Colonia"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("DarkKitchen.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarkKitchen.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.Product", b =>
                {
                    b.HasOne("DarkKitchen.Domain.Entities.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.User", b =>
                {
                    b.HasOne("DarkKitchen.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProductPromotions", b =>
                {
                    b.HasOne("DarkKitchen.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarkKitchen.Domain.Entities.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("DarkKitchen.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarkKitchen.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarkKitchen.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
